database:
  host: localhost
  port: 5432
  dbName: postgres
  dbuser: pdoeflpnysznyi
  password: 200015
  sslenable: disable
  # sslenable should be enable or disable

redis:
 addr: localhost:6379
 password: capregsoft



SMTP:
  hostName: mybidify
  mailAddress: teammybidify@gmail.com
  password: mybidify786
  smtpHost: smtp.gmail.com
  smtpPort: 587

